name: Extract Nasdaq Volume Daily

on:
  schedule:
    # Exécution tous les jours à 22h00 UTC
    - cron: '0 22 * * *'
  workflow_dispatch:   # Permet de le lancer manuellement

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # sécurité
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r extraction/requirements.txt

      - name: Run extraction script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: nasdaq100-volume-data
        run: python extraction/script.py